FROM node:20-alpine AS base
RUN npm install -g pnpm@9

# ── Builder stage ───────────────────────────────────────────────────────
FROM base AS builder
WORKDIR /app

# Copy workspace config
COPY package.json pnpm-workspace.yaml tsconfig.base.json ./

# Copy lockfile if present (optional — generated by `pnpm install` locally)
COPY pnpm-lock.yaml* ./

# Copy package manifests for dependency caching
COPY packages/types/package.json ./packages/types/
COPY apps/api/package.json ./apps/api/

# Install all dependencies (use lockfile when available, fall back otherwise)
RUN if [ -f pnpm-lock.yaml ]; then pnpm install --frozen-lockfile; else pnpm install; fi

# Copy source
COPY packages/types/ ./packages/types/
COPY apps/api/ ./apps/api/

# Generate Prisma client
RUN pnpm --filter @devsecops/api db:generate

# Build TypeScript
RUN pnpm --filter @devsecops/api build

# ── Migrate stage (runs prisma migrate deploy — uses builder so prisma CLI is available) ──
FROM builder AS migrate
WORKDIR /app
CMD ["pnpm", "--filter", "@devsecops/api", "db:migrate:deploy"]

# ── Runtime stage ───────────────────────────────────────────────────────
FROM node:20-alpine AS runtime
RUN npm install -g pnpm@9

WORKDIR /app

# Create non-root user
RUN addgroup -g 1001 -S nodejs && adduser -S nodeuser -u 1001 -G nodejs

# Copy workspace config and package manifests
COPY package.json pnpm-workspace.yaml ./
COPY pnpm-lock.yaml* ./
COPY packages/types/package.json ./packages/types/
COPY apps/api/package.json ./apps/api/

# Install production dependencies only
RUN if [ -f pnpm-lock.yaml ]; then pnpm install --frozen-lockfile --prod; else pnpm install --prod; fi

# Copy built output and Prisma artifacts
COPY --from=builder /app/apps/api/dist ./apps/api/dist
COPY --from=builder /app/apps/api/node_modules/.prisma ./apps/api/node_modules/.prisma
COPY apps/api/prisma ./apps/api/prisma

USER nodeuser

EXPOSE 3000

CMD ["node", "apps/api/dist/server.js"]
